version: '3'

services:
  mongo:
    container_name: mongo-dev
    image: mongo:4.2.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=developer
    ports:
      - 27017:27017
    volumes:
      - ./data/dev/mongo:/data/db
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
