version: '3'

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - '3001:3001'

networks:
  app-network:
    driver: bridge
